theme: jekyll-theme-minimal

title: Arquitecto de software (Master en cyberseguridad)
logo: /badge/avatar.png
description: Si lo piensas lo puedes hacer
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "default", "dirt", "neon", "mint", "plum" "sunrise"